# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diaAddProg.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_diaAddProg(object):
    def setupUi(self, diaAddProg):
        diaAddProg.setObjectName("diaAddProg")
        diaAddProg.resize(475, 325)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/Arcadia.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        diaAddProg.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(diaAddProg)
        self.buttonBox.setGeometry(QtCore.QRect(40, 270, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tbxName = QtWidgets.QLineEdit(diaAddProg)
        self.tbxName.setGeometry(QtCore.QRect(50, 80, 113, 20))
        self.tbxName.setObjectName("tbxName")
        self.tbxLocation = QtWidgets.QLineEdit(diaAddProg)
        self.tbxLocation.setGeometry(QtCore.QRect(200, 80, 141, 20))
        self.tbxLocation.setClearButtonEnabled(False)
        self.tbxLocation.setObjectName("tbxLocation")
        self.tbtnLocation = QtWidgets.QToolButton(diaAddProg)
        self.tbtnLocation.setGeometry(QtCore.QRect(340, 80, 25, 19))
        self.tbtnLocation.setObjectName("tbtnLocation")
        self.tbxDescription = QtWidgets.QPlainTextEdit(diaAddProg)
        self.tbxDescription.setGeometry(QtCore.QRect(50, 120, 311, 81))
        self.tbxDescription.setObjectName("tbxDescription")
        self.tbtnItemLocation = QtWidgets.QToolButton(diaAddProg)
        self.tbtnItemLocation.setGeometry(QtCore.QRect(340, 210, 25, 19))
        self.tbtnItemLocation.setObjectName("tbtnItemLocation")
        self.tbxItemLocation = QtWidgets.QLineEdit(diaAddProg)
        self.tbxItemLocation.setGeometry(QtCore.QRect(200, 210, 141, 20))
        self.tbxItemLocation.setClearButtonEnabled(False)
        self.tbxItemLocation.setObjectName("tbxItemLocation")
        self.iconView = QtWidgets.QLabel(diaAddProg)
        self.iconView.setGeometry(QtCore.QRect(140, 200, 41, 41))
        self.iconView.setObjectName("iconView")
        self.gbxType = QtWidgets.QGroupBox(diaAddProg)
        self.gbxType.setGeometry(QtCore.QRect(380, 10, 91, 251))
        self.gbxType.setObjectName("gbxType")
        self.rbnAntivirus = QtWidgets.QRadioButton(self.gbxType)
        self.rbnAntivirus.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.rbnAntivirus.setChecked(True)
        self.rbnAntivirus.setObjectName("rbnAntivirus")
        self.rbnAntimalware = QtWidgets.QRadioButton(self.gbxType)
        self.rbnAntimalware.setGeometry(QtCore.QRect(10, 80, 82, 17))
        self.rbnAntimalware.setObjectName("rbnAntimalware")
        self.rbnClean = QtWidgets.QRadioButton(self.gbxType)
        self.rbnClean.setGeometry(QtCore.QRect(10, 120, 82, 17))
        self.rbnClean.setObjectName("rbnClean")
        self.rbnSetup = QtWidgets.QRadioButton(self.gbxType)
        self.rbnSetup.setGeometry(QtCore.QRect(10, 160, 82, 17))
        self.rbnSetup.setObjectName("rbnSetup")
        self.rbnTools = QtWidgets.QRadioButton(self.gbxType)
        self.rbnTools.setGeometry(QtCore.QRect(10, 200, 82, 17))
        self.rbnTools.setObjectName("rbnTools")
        self.gbxOS = QtWidgets.QGroupBox(diaAddProg)
        self.gbxOS.setGeometry(QtCore.QRect(50, 10, 311, 41))
        self.gbxOS.setObjectName("gbxOS")
        self.rbnWindows = QtWidgets.QRadioButton(self.gbxOS)
        self.rbnWindows.setGeometry(QtCore.QRect(30, 20, 71, 17))
        self.rbnWindows.setChecked(True)
        self.rbnWindows.setObjectName("rbnWindows")
        self.rbnMac = QtWidgets.QRadioButton(self.gbxOS)
        self.rbnMac.setGeometry(QtCore.QRect(120, 20, 61, 17))
        self.rbnMac.setObjectName("rbnMac")
        self.rbnLinux = QtWidgets.QRadioButton(self.gbxOS)
        self.rbnLinux.setGeometry(QtCore.QRect(220, 20, 51, 17))
        self.rbnLinux.setObjectName("rbnLinux")
        self.tbxURL = QtWidgets.QLineEdit(diaAddProg)
        self.tbxURL.setGeometry(QtCore.QRect(62, 240, 281, 20))
        self.tbxURL.setObjectName("tbxURL")

        self.retranslateUi(diaAddProg)
        self.buttonBox.accepted.connect(diaAddProg.accept)
        self.buttonBox.rejected.connect(diaAddProg.reject)
        QtCore.QMetaObject.connectSlotsByName(diaAddProg)

    def retranslateUi(self, diaAddProg):
        _translate = QtCore.QCoreApplication.translate
        diaAddProg.setWindowTitle(_translate("diaAddProg", "Add Program"))
        self.tbxName.setPlaceholderText(_translate("diaAddProg", "Name"))
        self.tbxLocation.setPlaceholderText(_translate("diaAddProg", "Location"))
        self.tbtnLocation.setText(_translate("diaAddProg", "..."))
        self.tbxDescription.setPlaceholderText(_translate("diaAddProg", "Description"))
        self.tbtnItemLocation.setText(_translate("diaAddProg", "..."))
        self.tbxItemLocation.setPlaceholderText(_translate("diaAddProg", "Icon Location"))
        self.iconView.setText(_translate("diaAddProg", "Default"))
        self.gbxType.setTitle(_translate("diaAddProg", "Type"))
        self.rbnAntivirus.setText(_translate("diaAddProg", "Antivirus"))
        self.rbnAntimalware.setText(_translate("diaAddProg", "Antimalware"))
        self.rbnClean.setText(_translate("diaAddProg", "Clean"))
        self.rbnSetup.setText(_translate("diaAddProg", "Setup"))
        self.rbnTools.setText(_translate("diaAddProg", "Tools"))
        self.gbxOS.setTitle(_translate("diaAddProg", "Operating System"))
        self.rbnWindows.setText(_translate("diaAddProg", "Windows"))
        self.rbnMac.setText(_translate("diaAddProg", "Mac OS"))
        self.rbnLinux.setText(_translate("diaAddProg", "Linux"))
        self.tbxURL.setPlaceholderText(_translate("diaAddProg", "URL"))

