# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progEditor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmXMLEdit(object):
    def setupUi(self, frmXMLEdit):
        frmXMLEdit.setObjectName("frmXMLEdit")
        frmXMLEdit.resize(692, 467)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/Arcadia.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmXMLEdit.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(frmXMLEdit)
        self.centralwidget.setObjectName("centralwidget")
        self.lstMod = QtWidgets.QListWidget(self.centralwidget)
        self.lstMod.setGeometry(QtCore.QRect(370, 30, 311, 301))
        self.lstMod.setObjectName("lstMod")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(380, 340, 61, 23))
        self.btnAdd.setObjectName("btnAdd")
        self.btnRemove = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemove.setGeometry(QtCore.QRect(450, 340, 61, 23))
        self.btnRemove.setObjectName("btnRemove")
        self.lblCurrent = QtWidgets.QLabel(self.centralwidget)
        self.lblCurrent.setGeometry(QtCore.QRect(120, 10, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lblCurrent.setFont(font)
        self.lblCurrent.setObjectName("lblCurrent")
        self.lblModified = QtWidgets.QLabel(self.centralwidget)
        self.lblModified.setGeometry(QtCore.QRect(480, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lblModified.setFont(font)
        self.lblModified.setObjectName("lblModified")
        self.lstCurrent = QtWidgets.QListWidget(self.centralwidget)
        self.lstCurrent.setGeometry(QtCore.QRect(10, 30, 301, 301))
        self.lstCurrent.setObjectName("lstCurrent")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(570, 390, 91, 31))
        self.btnExit.setObjectName("btnExit")
        self.chkChanges = QtWidgets.QCheckBox(self.centralwidget)
        self.chkChanges.setGeometry(QtCore.QRect(310, 340, 70, 17))
        self.chkChanges.setObjectName("chkChanges")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(140, 400, 151, 23))
        self.btnSave.setObjectName("btnSave")
        self.btnBackup = QtWidgets.QPushButton(self.centralwidget)
        self.btnBackup.setGeometry(QtCore.QRect(20, 340, 75, 23))
        self.btnBackup.setObjectName("btnBackup")
        self.btnLoad = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoad.setGeometry(QtCore.QRect(620, 340, 61, 23))
        self.btnLoad.setObjectName("btnLoad")
        self.lblModDiff = QtWidgets.QLabel(self.centralwidget)
        self.lblModDiff.setGeometry(QtCore.QRect(320, 70, 41, 20))
        self.lblModDiff.setAlignment(QtCore.Qt.AlignCenter)
        self.lblModDiff.setObjectName("lblModDiff")
        self.lblCurrentDiff = QtWidgets.QLabel(self.centralwidget)
        self.lblCurrentDiff.setGeometry(QtCore.QRect(320, 180, 41, 20))
        self.lblCurrentDiff.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCurrentDiff.setObjectName("lblCurrentDiff")
        self.lblRightArrow = QtWidgets.QLabel(self.centralwidget)
        self.lblRightArrow.setGeometry(QtCore.QRect(320, 100, 41, 21))
        self.lblRightArrow.setText("")
        self.lblRightArrow.setPixmap(QtGui.QPixmap("Icons/rightarrow.png"))
        self.lblRightArrow.setScaledContents(True)
        self.lblRightArrow.setObjectName("lblRightArrow")
        self.lblLeftArrow = QtWidgets.QLabel(self.centralwidget)
        self.lblLeftArrow.setGeometry(QtCore.QRect(320, 210, 41, 21))
        self.lblLeftArrow.setText("")
        self.lblLeftArrow.setPixmap(QtGui.QPixmap("Icons/Left-Arrow-PNG-File.png"))
        self.lblLeftArrow.setScaledContents(True)
        self.lblLeftArrow.setObjectName("lblLeftArrow")
        self.btnChange = QtWidgets.QPushButton(self.centralwidget)
        self.btnChange.setGeometry(QtCore.QRect(520, 340, 71, 23))
        self.btnChange.setObjectName("btnChange")
        self.btnImport = QtWidgets.QPushButton(self.centralwidget)
        self.btnImport.setGeometry(QtCore.QRect(350, 400, 151, 23))
        self.btnImport.setObjectName("btnImport")
        frmXMLEdit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(frmXMLEdit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 692, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        frmXMLEdit.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(frmXMLEdit)
        self.statusbar.setObjectName("statusbar")
        frmXMLEdit.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(frmXMLEdit)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(frmXMLEdit)
        self.actionClose.setObjectName("actionClose")
        self.actionSave = QtWidgets.QAction(frmXMLEdit)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(frmXMLEdit)
        QtCore.QMetaObject.connectSlotsByName(frmXMLEdit)

    def retranslateUi(self, frmXMLEdit):
        _translate = QtCore.QCoreApplication.translate
        frmXMLEdit.setWindowTitle(_translate("frmXMLEdit", "Program Editor"))
        self.btnAdd.setText(_translate("frmXMLEdit", "Add"))
        self.btnRemove.setText(_translate("frmXMLEdit", "Remove"))
        self.lblCurrent.setText(_translate("frmXMLEdit", "Current"))
        self.lblModified.setText(_translate("frmXMLEdit", "Modified"))
        self.btnExit.setText(_translate("frmXMLEdit", "Exit"))
        self.chkChanges.setText(_translate("frmXMLEdit", "Changes"))
        self.btnSave.setText(_translate("frmXMLEdit", "Save"))
        self.btnBackup.setText(_translate("frmXMLEdit", "Backup"))
        self.btnLoad.setText(_translate("frmXMLEdit", "Load"))
        self.lblModDiff.setText(_translate("frmXMLEdit", "0"))
        self.lblCurrentDiff.setText(_translate("frmXMLEdit", "0"))
        self.btnChange.setText(_translate("frmXMLEdit", "View/Change"))
        self.btnImport.setText(_translate("frmXMLEdit", "Import"))
        self.menuFile.setTitle(_translate("frmXMLEdit", "File"))
        self.actionOpen.setText(_translate("frmXMLEdit", "Open"))
        self.actionClose.setText(_translate("frmXMLEdit", "Close"))
        self.actionSave.setText(_translate("frmXMLEdit", "Save"))

